### ISSUE TITLE
weights release

### ISSUE THREAD

**Issue by amosyou** [GuoLanqing/Self-Cascade#1]
Hi,

Thanks for the amazing work! I was wondering if there's plans on releasing the model weights after the code release? It wasn't mentioned in the paper so I wanted to reach out about that.

Thanks!

**Comment by GuoLanqing** [comment]
Thanks for your interest. The code will be released soon.

**Comment by ezacngm** [comment]
Hi Guo, 

Your work is amazing and enlightening. I am wondering how the time-aware feature was built up and implemented. I would like to sincerely inquire when the codes will be released so that I can learn from your wunderbar idea:)

I'm really looking forward to the codes:)

Thanks.
